### ISSUE TITLE
All Cookbook builds currently broken

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/cookbook-template#100]
As of four days ago, it looks like all Cookbook including this Template are failing their nightly builds.

See build log [here](https://github.com/ProjectPythia/cookbook-template/actions/runs/3804006970/jobs/6470876935#step:13:42) where this error is raised:
```
pkg_resources.ContextualVersionConflict: (jsonschema 3.2.0 (/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages), Requirement.parse('jsonschema[format-nongpl]>=4.3.0'), {'jupyter-events'})
```

**Comment by brian-rose** [comment]
Trying to run `jupyter-book build` locally on my laptop with a fresh environment yielded the same error.

**Comment by brian-rose** [comment]
@ProjectPythia/infrastructure hopefully we can get this fixed this week given the AMS meeting coming up.

**Comment by brian-rose** [comment]
Possibly related to https://github.com/ProjectPythia/intake-cookbook/issues/26?

**Comment by brian-rose** [comment]
Interestingly, the Foundations book (which uses a very similar stack of dependencies) is still passing its nightly builds: https://github.com/ProjectPythia/pythia-foundations/actions/runs/3826152298/jobs/6509714548

**Comment by jnmorley** [comment]
I tried cloning the radar-cookbook, which seemed to be having this issue. After creating the Conda environment, I was not able to start Jupyter Lab. It would throw a `ModuleNotFoundError: No module named 'jsonschema.protocols'`. Comparing the Conda environment with a working environment I created a few days ago, I noticed that jupyter_server had updated from version 1.23.4 to version 2.0.6. Downgrading jupyter_server back to 1.23.4 seemed to fix the issue. I am not sure exactly what the problem is, but downgrading jupyter_server might work as a temporary work around for this issue. From what I can tell, jupyter_server version 2.0.6 tries to use a module in jsonschema that was added around jsonschema=4.3.0, but Jupyter Book requires a version of jsonschema <4.0.0

**Comment by brian-rose** [comment]
In #101 I added
```
- jupyter_server<2
```
to the `environment.yml` file and that resolved the build problem.

This does seem like a bandaid solution since there's nothing Pythia-specific that triggered this error. I think it's worth tracing the problem upstream and seeing where we can report it, or if it's already being tracked somewhere.

**Comment by jukent** [comment]
Should I go through and add this dependency to the other cookbooks?

**Comment by brian-rose** [comment]
> Should I go through and add this dependency to the other cookbooks?

Yes, please @jukent that would be great.

If you have time, it would also be great if you could do some digging to see if this problem has been reported anywhere, e.g. jupyterlab or jupyterbook repos.

**Comment by mgrover1** [comment]
I suspect these issues are related to one that was opened ~13 hours ago https://github.com/executablebooks/jupyter-book/issues/1902

**Comment by jukent** [comment]
They all look to be passing to me now? I didn't make any changes.

**Comment by brian-rose** [comment]
> They all look to be passing to me now? I didn't make any changes.

The cookbooks that are building via binder are not currently affected by this issue because they are using an earlier image cached on the binder. I assume they would probably fail with the same issue if we tried to build a new image with a new environment. Unfortunately we don't have a good way to test this right now.

**Comment by jukent** [comment]
I'm not sure I fully understand - but it sounds like all the Cookbooks displayed in the gallery are unaffected (except maybe the intake one).

**Comment by brian-rose** [comment]
> I'm not sure I fully understand - but it sounds like all the Cookbooks displayed in the gallery are unaffected (except maybe the intake one).

The Radar cookbook was affected, but it was already fixed this morning in https://github.com/ProjectPythia/radar-cookbook/pull/84

**Comment by brian-rose** [comment]
There are several gaps in our nightly testing strategy. One of them is this inconsistency between what gets tested when we execute the notebooks on GitHub Actions vs on the Binder. On Github Actions, we make a fresh new conda environment every calendar day, or if there are any changes to the environment file. On Binder, we use the cached image associated with the main branch of the repo. This means that the tests run much quicker since we don't have to solve a new environment and build a new docker image, but in some cases (like right now) we are then running the notebooks in a different, out-of-date environment relative to what conda would create for us today -- usually because some new package versions became available upstream. It's a bit of a double-edged sword -- the cached Binder image means that we can run and test the *content* of our notebooks, and keep doing that even when something breaks upstream -- but we're not testing the reproducibility of the environment.

Something to think about in the bigger picture of what our health checking suite should ideally cover.

**Comment by jukent** [comment]
Thanks for explaining. Topic for next IWG?

**Comment by clyne** [comment]
Thanks @brian-rose, @jukent, @jnmorley, @mgrover1 for unraveling this.

**Comment by brian-rose** [comment]
This was left open in order to improve our testing strategy to do a better job of catching this type of failure. We'll continue that discussion elsewhere. Closing this now.
