### ISSUE TITLE
Would a .pre-commit file be helpful?

### ISSUE THREAD

**Issue by norlandrhagen** [ProjectPythia/cookbook-template#102]
Hi there, 

Wondering if the use of `pre-commit` has been considered? It might help to enforce some standardization between cookbooks. If there is any interest, I would be happy to add a config file to the template.

@ktyle @mgrover1

**Comment by brian-rose** [comment]
Good question @norlandrhagen! We are already using pre-commit on some of our other repos, such as [Pythia Foundations](https://github.com/ProjectPythia/pythia-foundations/blob/main/.pre-commit-config.yaml).

It makes sense to me to use the same tool for the Cookbooks to ensure some standardization of code style.

**Comment by brian-rose** [comment]
Closing this with the merger of #103, but just noting here that we might revisit after we see how the pre-commit autoupdates go.
