### ISSUE TITLE
Working from branches on this repo creates confusion

### ISSUE THREAD

**Issue by dcamron** [ProjectPythia/cookbook-template#186]
![image](https://github.com/ProjectPythia/cookbook-template/assets/24628426/980e91b3-653e-44df-b720-c2dfd9dff94b)

We should prioritize closing branches ASAP or working only from forks to open PRs on this repo. Our instructions require folks copy all branches with the template (to get `gh-pages`) and then they end up with these GitHub notifications. Julia's branch was stale from an old PR, so I went ahead and deleted it. The @brian-rose branch tied to #174 has been around for a while and is in open discussion. I might recommend moving that branch to your fork or us pushing forward to resolve that issue more quickly. I'll tie this issue to that PR, but we should make an effort to avoid this in the future as well.

**Comment by brian-rose** [comment]
@dcamron good point, I think these branches get created when I do a quick "one-off" edit on GitHub but I see that it creates confusion.

I'm not sure how to move an existing branch to my personal fork and preserve the discussion on the open PR. I'll look it up.
